version: "3.6"

services:
  # run samson in test mode
  samson-test: &test
    build:
      context: ../
      dockerfile: .buildkite/Dockerfile
    environment: &test_env
      # CI envs
      CI:
      TRAVIS: 1
      # CI envs For Buildkite
      BUILDKITE_PARALLEL_JOB:
      BUILDKITE_PARALLEL_JOB_COUNT:
      # Defaults
      SILENCE_MIGRATIONS: 1
      RAILS_ENV: test

  # run samson in test mode against sqlite
  samson-test-sqlite:
    <<: *test
    environment:
      <<: *test_env
      DATABASE_URL: "sqlite3:///app/db/test.sqlite3"
    command: ["bundle", "exec", "rake", "db:create", "db:migrate", "default"]

  # run samson in test with mysql
  samson-test-mysql:
    <<: *test
    environment:
      <<: *test_env
      DATABASE_URL: "mysql2://root@mysql/samson_test?reconnect=true"
      USE_UTF8MB4: 1
    command: ["await", "-v", "mysql://root@mysql:3306", "--", "bundle", "exec", "rake", "db:create", "db:migrate", "default"]
    depends_on:
      - mysql

  # run samson in test with mysql (no plugins)
  samson-test-mysql-no-plugins:
    <<: *test
    environment:
      <<: *test_env
      PLUGINS: ""
      DATABASE_URL: "mysql2://root@mysql/samson_test?reconnect=true"
      USE_UTF8MB4: 1
    command: ["await", "-v", "mysql://root@mysql:3306", "--", "bundle", "exec", "rake", "db:create", "test:migrate_without_plugins"]
    depends_on:
      - mysql

  # run samson in test with postgres
  samson-test-postgres:
    <<: *test
    environment:
      <<: *test_env
      PLUGINS: ""
      DATABASE_URL: "postgresql://postgres@postgres/samson_test"
      SILENCE_MIGRATIONS: 1
      RAILS_ENV: test
    command: ["await", "-v", "tcp4://postgres:5432", "--", "bundle", "exec", "rake", "db:create", "db:migrate", "default"]
    depends_on:
      - postgres

  # types of database to test against
  # ---------------------------------

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"

  postgres:
    image: postgres:9.2-alpine
    environment:
      POSTGRES_PASSWORD: ""
